services:
  tigerbeetle:
    image: ghcr.io/tigerbeetle/tigerbeetle
    command: start --addresses=0.0.0.0:3001 --replica=0 --replica-count=1 /data/0_0.tigerbeetle
    ports:
      - "3001:3001"
    volumes:
      - ./data:/data
    security_opt:
      - seccomp=unconfined
