// proto/financial.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/financial.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Requisição para criar uma conta
type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Ledger        uint32                 `protobuf:"varint,2,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Flags         uint32                 `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"`
	UserData      string                 `protobuf:"bytes,4,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_proto_financial_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_financial_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_financial_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateAccountRequest) GetLedger() uint32 {
	if x != nil {
		return x.Ledger
	}
	return 0
}

func (x *CreateAccountRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *CreateAccountRequest) GetUserData() string {
	if x != nil {
		return x.UserData
	}
	return ""
}

// Requisição para buscar uma conta
type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_proto_financial_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_financial_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_financial_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Resposta de uma operação com conta
type AccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          uint32                 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Ledger        uint32                 `protobuf:"varint,3,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Balance       int64                  `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	Flags         uint32                 `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`
	UserData      string                 `protobuf:"bytes,6,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	Success       bool                   `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_proto_financial_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_financial_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_financial_proto_rawDescGZIP(), []int{2}
}

func (x *AccountResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AccountResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AccountResponse) GetLedger() uint32 {
	if x != nil {
		return x.Ledger
	}
	return 0
}

func (x *AccountResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *AccountResponse) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *AccountResponse) GetUserData() string {
	if x != nil {
		return x.UserData
	}
	return ""
}

func (x *AccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AccountResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Requisição para criar uma transferência
type CreateTransferRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DebitAccountId  uint64                 `protobuf:"varint,1,opt,name=debit_account_id,json=debitAccountId,proto3" json:"debit_account_id,omitempty"`
	CreditAccountId uint64                 `protobuf:"varint,2,opt,name=credit_account_id,json=creditAccountId,proto3" json:"credit_account_id,omitempty"`
	Amount          uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Ledger          uint32                 `protobuf:"varint,4,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Code            string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Flags           uint32                 `protobuf:"varint,6,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_proto_financial_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_financial_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_financial_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTransferRequest) GetDebitAccountId() uint64 {
	if x != nil {
		return x.DebitAccountId
	}
	return 0
}

func (x *CreateTransferRequest) GetCreditAccountId() uint64 {
	if x != nil {
		return x.CreditAccountId
	}
	return 0
}

func (x *CreateTransferRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransferRequest) GetLedger() uint32 {
	if x != nil {
		return x.Ledger
	}
	return 0
}

func (x *CreateTransferRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateTransferRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

// Requisição para buscar uma transferência
type GetTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferRequest) Reset() {
	*x = GetTransferRequest{}
	mi := &file_proto_financial_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferRequest) ProtoMessage() {}

func (x *GetTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_financial_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferRequest.ProtoReflect.Descriptor instead.
func (*GetTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_financial_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransferRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Resposta de uma operação com transferência
type TransferResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DebitAccountId  uint64                 `protobuf:"varint,2,opt,name=debit_account_id,json=debitAccountId,proto3" json:"debit_account_id,omitempty"`
	CreditAccountId uint64                 `protobuf:"varint,3,opt,name=credit_account_id,json=creditAccountId,proto3" json:"credit_account_id,omitempty"`
	Amount          uint64                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Ledger          uint32                 `protobuf:"varint,5,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Code            string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	Flags           uint32                 `protobuf:"varint,7,opt,name=flags,proto3" json:"flags,omitempty"`
	Timestamp       uint32                 `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Success         bool                   `protobuf:"varint,9,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_proto_financial_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_financial_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_financial_proto_rawDescGZIP(), []int{5}
}

func (x *TransferResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransferResponse) GetDebitAccountId() uint64 {
	if x != nil {
		return x.DebitAccountId
	}
	return 0
}

func (x *TransferResponse) GetCreditAccountId() uint64 {
	if x != nil {
		return x.CreditAccountId
	}
	return 0
}

func (x *TransferResponse) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferResponse) GetLedger() uint32 {
	if x != nil {
		return x.Ledger
	}
	return 0
}

func (x *TransferResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TransferResponse) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *TransferResponse) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_financial_proto protoreflect.FileDescriptor

const file_proto_financial_proto_rawDesc = "" +
	"\n" +
	"\x15proto/financial.proto\x12\tfinancial\"u\n" +
	"\x14CreateAccountRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x16\n" +
	"\x06ledger\x18\x02 \x01(\rR\x06ledger\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\rR\x05flags\x12\x1b\n" +
	"\tuser_data\x18\x04 \x01(\tR\buserData\"#\n" +
	"\x11GetAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xd9\x01\n" +
	"\x0fAccountResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\rR\x04code\x12\x16\n" +
	"\x06ledger\x18\x03 \x01(\rR\x06ledger\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x03R\abalance\x12\x14\n" +
	"\x05flags\x18\x05 \x01(\rR\x05flags\x12\x1b\n" +
	"\tuser_data\x18\x06 \x01(\tR\buserData\x12\x18\n" +
	"\asuccess\x18\a \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\"\xc7\x01\n" +
	"\x15CreateTransferRequest\x12(\n" +
	"\x10debit_account_id\x18\x01 \x01(\x04R\x0edebitAccountId\x12*\n" +
	"\x11credit_account_id\x18\x02 \x01(\x04R\x0fcreditAccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x12\x16\n" +
	"\x06ledger\x18\x04 \x01(\rR\x06ledger\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x14\n" +
	"\x05flags\x18\x06 \x01(\rR\x05flags\"$\n" +
	"\x12GetTransferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xaf\x02\n" +
	"\x10TransferResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12(\n" +
	"\x10debit_account_id\x18\x02 \x01(\x04R\x0edebitAccountId\x12*\n" +
	"\x11credit_account_id\x18\x03 \x01(\x04R\x0fcreditAccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\x12\x16\n" +
	"\x06ledger\x18\x05 \x01(\rR\x06ledger\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\x12\x14\n" +
	"\x05flags\x18\a \x01(\rR\x05flags\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\rR\ttimestamp\x12\x18\n" +
	"\asuccess\x18\t \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage2\xc4\x02\n" +
	"\x10FinancialService\x12L\n" +
	"\rCreateAccount\x12\x1f.financial.CreateAccountRequest\x1a\x1a.financial.AccountResponse\x12F\n" +
	"\n" +
	"GetAccount\x12\x1c.financial.GetAccountRequest\x1a\x1a.financial.AccountResponse\x12O\n" +
	"\x0eCreateTransfer\x12 .financial.CreateTransferRequest\x1a\x1b.financial.TransferResponse\x12I\n" +
	"\vGetTransfer\x12\x1d.financial.GetTransferRequest\x1a\x1b.financial.TransferResponseB\x1bZ\x19tigerbeetle-service/protob\x06proto3"

var (
	file_proto_financial_proto_rawDescOnce sync.Once
	file_proto_financial_proto_rawDescData []byte
)

func file_proto_financial_proto_rawDescGZIP() []byte {
	file_proto_financial_proto_rawDescOnce.Do(func() {
		file_proto_financial_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_financial_proto_rawDesc), len(file_proto_financial_proto_rawDesc)))
	})
	return file_proto_financial_proto_rawDescData
}

var file_proto_financial_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_financial_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),  // 0: financial.CreateAccountRequest
	(*GetAccountRequest)(nil),     // 1: financial.GetAccountRequest
	(*AccountResponse)(nil),       // 2: financial.AccountResponse
	(*CreateTransferRequest)(nil), // 3: financial.CreateTransferRequest
	(*GetTransferRequest)(nil),    // 4: financial.GetTransferRequest
	(*TransferResponse)(nil),      // 5: financial.TransferResponse
}
var file_proto_financial_proto_depIdxs = []int32{
	0, // 0: financial.FinancialService.CreateAccount:input_type -> financial.CreateAccountRequest
	1, // 1: financial.FinancialService.GetAccount:input_type -> financial.GetAccountRequest
	3, // 2: financial.FinancialService.CreateTransfer:input_type -> financial.CreateTransferRequest
	4, // 3: financial.FinancialService.GetTransfer:input_type -> financial.GetTransferRequest
	2, // 4: financial.FinancialService.CreateAccount:output_type -> financial.AccountResponse
	2, // 5: financial.FinancialService.GetAccount:output_type -> financial.AccountResponse
	5, // 6: financial.FinancialService.CreateTransfer:output_type -> financial.TransferResponse
	5, // 7: financial.FinancialService.GetTransfer:output_type -> financial.TransferResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_financial_proto_init() }
func file_proto_financial_proto_init() {
	if File_proto_financial_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_financial_proto_rawDesc), len(file_proto_financial_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_financial_proto_goTypes,
		DependencyIndexes: file_proto_financial_proto_depIdxs,
		MessageInfos:      file_proto_financial_proto_msgTypes,
	}.Build()
	File_proto_financial_proto = out.File
	file_proto_financial_proto_goTypes = nil
	file_proto_financial_proto_depIdxs = nil
}
